defaults:
  - base_mapping

_target_: rayfronts.mapping.SemanticVoxelMap

# Length of a side of a voxel in meters.
vox_size: 0.3

# How many points to project per frame. Set to -1 to project all valid depth
# points.
max_pts_per_frame: 1000

# How often do we aggregate voxels into the global representation.
# Setting to 10, will accumulate point clouds from 10 frames before 
# voxelization.
vox_accum_period: 8

feat_compressor: ${oc.select:feat_compressor, null}

interp_mode: ${interp_mode}