defaults:
  - base_dataset

_target_: rayfronts.datasets.ScanNetDataset

# Path to the root processed scannet directory.
path: ???

# Name of the scene from scannet. E.g "scene0518_00".
scene_name: scene0518_00

# Whether to load semantic segmentation labels or not.
load_semseg: True
