defaults:
  - base_encoder

_target_: rayfronts.image_encoders.ResRadioEncoder

# Choose from "radio_v2.5-x" where x can be b,l, or g. More models can be found 
# on https://github.com/NVlabs/RADIO/
model_version: radio_v2.5-l

# If text_query is not null, then lang_model cannot be null
lang_model: siglip

# Tuple of ints (height, width) of the input images. Needed to initialize the
# guassian attention window.
input_resolution: ${dataset.rgb_resolution}

# Standard deviation of the gaussian kernel.
gaussian_std: 5.0

# Whether to return radio features which are not language aligned or whether to 
# project them to the language aligned space directly. If True, then the user 
# can always later use the functions `align_global_features_with_language` or 
# `align_spatial_features_with_language` to project the radio features to be 
# language aligned.
return_radio_features: True

# Whether to compile the model.
compile: ${compile}

# Whether to use automatic mixed percision when inferring.
amp: ${amp}

# Sliding window inference parameters (for large images)
# Set use_sliding_window to True to enable sliding window inference
use_sliding_window: True
slide_crop_size: 336
slide_stride: 112

use_rcs: True
use_sfr: False
rcs_layers: [9,10]
attn_rcs_weights: [2.0, 0.3]
attn_sfr_weights: [2.1, 0.6]
temp_thd: 0.20
delete_same_entity: True